//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exitosw.Payroll.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://testing.solucionfactible.com/ws/services/Timbrado.TimbradoHttpsSoap11Endp" +
            "oint/")]
        public string Exitosw_Payroll_Core_WsSolocionFactibleTest_Timbrado {
            get {
                return ((string)(this["Exitosw_Payroll_Core_WsSolocionFactibleTest_Timbrado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://solucionfactible.com/ws/services/Cancelacion.CancelacionHttpsSoap11Endpoi" +
            "nt/")]
        public string Exitosw_Payroll_Core_WsSolucionfactibleCancelar_Cancelacion {
            get {
                return ((string)(this["Exitosw_Payroll_Core_WsSolucionfactibleCancelar_Cancelacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://solucionfactible.com/ws/services/Timbrado.TimbradoHttpsSoap11Endpoint/")]
        public string Exitosw_Payroll_Core_WsSolucionfactible_Timbrado {
            get {
                return ((string)(this["Exitosw_Payroll_Core_WsSolucionfactible_Timbrado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc")]
        public string Exitosw_Payroll_Core_WebConsultarSat_ConsultaCFDIService {
            get {
                return ((string)(this["Exitosw_Payroll_Core_WebConsultarSat_ConsultaCFDIService"]));
            }
        }
    }
}
