//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Exitosw.Payroll.Core.WsSolucionfactibleCancelar {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CancelacionSoap11Binding", Namespace="http://ws.cfdi.solucionfactible.com")]
    public partial class Cancelacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getStatusCancelacionAsincronaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarSectorPrimarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSolicitudCancelacionAsincronoOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSolicitudCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarAsincronoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Cancelacion() {
            this.Url = global::Exitosw.Payroll.Core.Properties.Settings.Default.Exitosw_Payroll_Core_WsSolucionfactibleCancelar_Cancelacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getStatusCancelacionAsincronaCompletedEventHandler getStatusCancelacionAsincronaCompleted;
        
        /// <remarks/>
        public event cancelarSectorPrimarioCompletedEventHandler cancelarSectorPrimarioCompleted;
        
        /// <remarks/>
        public event enviarSolicitudCancelacionAsincronoCompletedEventHandler enviarSolicitudCancelacionAsincronoCompleted;
        
        /// <remarks/>
        public event enviarSolicitudCancelacionCompletedEventHandler enviarSolicitudCancelacionCompleted;
        
        /// <remarks/>
        public event cancelarCompletedEventHandler cancelarCompleted;
        
        /// <remarks/>
        public event cancelarAsincronoCompletedEventHandler cancelarAsincronoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getStatusCancelacionAsincrona", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StatusCancelacionResponse getStatusCancelacionAsincrona([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string transactionId, string rFC, [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)] KeyValue[] properties) {
            object[] results = this.Invoke("getStatusCancelacionAsincrona", new object[] {
                        usuario,
                        password,
                        transactionId,
                        properties});
            return ((StatusCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusCancelacionAsincronaAsync(string usuario, string password, string transactionId, KeyValue[] properties) {
            this.getStatusCancelacionAsincronaAsync(usuario, password, transactionId, properties, null);
        }
        
        /// <remarks/>
        public void getStatusCancelacionAsincronaAsync(string usuario, string password, string transactionId, KeyValue[] properties, object userState) {
            if ((this.getStatusCancelacionAsincronaOperationCompleted == null)) {
                this.getStatusCancelacionAsincronaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusCancelacionAsincronaOperationCompleted);
            }
            this.InvokeAsync("getStatusCancelacionAsincrona", new object[] {
                        usuario,
                        password,
                        transactionId,
                        properties}, this.getStatusCancelacionAsincronaOperationCompleted, userState);
        }
        
        private void OngetStatusCancelacionAsincronaOperationCompleted(object arg) {
            if ((this.getStatusCancelacionAsincronaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCancelacionAsincronaCompleted(this, new getStatusCancelacionAsincronaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarSectorPrimario", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StatusCancelacionResponse cancelarSectorPrimario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid) {
            object[] results = this.Invoke("cancelarSectorPrimario", new object[] {
                        usuario,
                        password,
                        uuid});
            return ((StatusCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarSectorPrimarioAsync(string usuario, string password, string uuid) {
            this.cancelarSectorPrimarioAsync(usuario, password, uuid, null);
        }
        
        /// <remarks/>
        public void cancelarSectorPrimarioAsync(string usuario, string password, string uuid, object userState) {
            if ((this.cancelarSectorPrimarioOperationCompleted == null)) {
                this.cancelarSectorPrimarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarSectorPrimarioOperationCompleted);
            }
            this.InvokeAsync("cancelarSectorPrimario", new object[] {
                        usuario,
                        password,
                        uuid}, this.cancelarSectorPrimarioOperationCompleted, userState);
        }
        
        private void OncancelarSectorPrimarioOperationCompleted(object arg) {
            if ((this.cancelarSectorPrimarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarSectorPrimarioCompleted(this, new cancelarSectorPrimarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:enviarSolicitudCancelacionAsincrono", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CancelacionAsincronoResponse enviarSolicitudCancelacionAsincrono([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] solicitud, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailNotifica, [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)] KeyValue[] properties) {
            object[] results = this.Invoke("enviarSolicitudCancelacionAsincrono", new object[] {
                        usuario,
                        password,
                        solicitud,
                        emailNotifica,
                        properties});
            return ((CancelacionAsincronoResponse)(results[0]));
        }

        internal StatusCancelacionResponse getStatusCancelacionAsincrona(string usuario, string passwordKey, string uUID, object p)
        {
            try {

              return  getStatusCancelacionAsincrona(usuario, passwordKey, uUID, null, null);
            }
            catch (Exception)
            {

                throw new NotImplementedException();
            }
            
           
        }

        /// <remarks/>
        public void enviarSolicitudCancelacionAsincronoAsync(string usuario, string password, byte[] solicitud, string emailNotifica, KeyValue[] properties) {
            this.enviarSolicitudCancelacionAsincronoAsync(usuario, password, solicitud, emailNotifica, properties, null);
        }
        
        /// <remarks/>
        public void enviarSolicitudCancelacionAsincronoAsync(string usuario, string password, byte[] solicitud, string emailNotifica, KeyValue[] properties, object userState) {
            if ((this.enviarSolicitudCancelacionAsincronoOperationCompleted == null)) {
                this.enviarSolicitudCancelacionAsincronoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSolicitudCancelacionAsincronoOperationCompleted);
            }
            this.InvokeAsync("enviarSolicitudCancelacionAsincrono", new object[] {
                        usuario,
                        password,
                        solicitud,
                        emailNotifica,
                        properties}, this.enviarSolicitudCancelacionAsincronoOperationCompleted, userState);
        }
        
        private void OnenviarSolicitudCancelacionAsincronoOperationCompleted(object arg) {
            if ((this.enviarSolicitudCancelacionAsincronoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSolicitudCancelacionAsincronoCompleted(this, new enviarSolicitudCancelacionAsincronoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:enviarSolicitudCancelacion", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StatusCancelacionResponse enviarSolicitudCancelacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] solicitud, [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)] KeyValue[] properties) {
            object[] results = this.Invoke("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitud,
                        properties});
            return ((StatusCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSolicitudCancelacionAsync(string usuario, string password, byte[] solicitud, KeyValue[] properties) {
            this.enviarSolicitudCancelacionAsync(usuario, password, solicitud, properties, null);
        }
        
        /// <remarks/>
        public void enviarSolicitudCancelacionAsync(string usuario, string password, byte[] solicitud, KeyValue[] properties, object userState) {
            if ((this.enviarSolicitudCancelacionOperationCompleted == null)) {
                this.enviarSolicitudCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSolicitudCancelacionOperationCompleted);
            }
            this.InvokeAsync("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitud,
                        properties}, this.enviarSolicitudCancelacionOperationCompleted, userState);
        }
        
        private void OnenviarSolicitudCancelacionOperationCompleted(object arg) {
            if ((this.enviarSolicitudCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSolicitudCancelacionCompleted(this, new enviarSolicitudCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelar", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StatusCancelacionResponse cancelar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derCertCSD, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derKeyCSD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD, [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)] KeyValue[] properties) {
            object[] results = this.Invoke("cancelar", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD,
                        properties});
            return ((StatusCancelacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsync(string usuario, string password, string rfcEmisor, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD, KeyValue[] properties) {
            this.cancelarAsync(usuario, password, rfcEmisor, uuids, derCertCSD, derKeyCSD, contrasenaCSD, properties, null);
        }
        
        /// <remarks/>
        public void cancelarAsync(string usuario, string password, string rfcEmisor, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD, KeyValue[] properties, object userState) {
            if ((this.cancelarOperationCompleted == null)) {
                this.cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarOperationCompleted);
            }
            this.InvokeAsync("cancelar", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD,
                        properties}, this.cancelarOperationCompleted, userState);
        }
        
        private void OncancelarOperationCompleted(object arg) {
            if ((this.cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCompleted(this, new cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarAsincrono", RequestNamespace="http://ws.cfdi.solucionfactible.com", ResponseNamespace="http://ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CancelacionAsincronoResponse cancelarAsincrono([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailNotifica, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] csdCer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] csdKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string csdPassword, [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)] KeyValue[] properties) {
            object[] results = this.Invoke("cancelarAsincrono", new object[] {
                        usuario,
                        password,
                        uuid,
                        rfcEmisor,
                        emailNotifica,
                        csdCer,
                        csdKey,
                        csdPassword,
                        properties});
            return ((CancelacionAsincronoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsincronoAsync(string usuario, string password, string uuid, string rfcEmisor, string emailNotifica, byte[] csdCer, byte[] csdKey, string csdPassword, KeyValue[] properties) {
            this.cancelarAsincronoAsync(usuario, password, uuid, rfcEmisor, emailNotifica, csdCer, csdKey, csdPassword, properties, null);
        }
        
        /// <remarks/>
        public void cancelarAsincronoAsync(string usuario, string password, string uuid, string rfcEmisor, string emailNotifica, byte[] csdCer, byte[] csdKey, string csdPassword, KeyValue[] properties, object userState) {
            if ((this.cancelarAsincronoOperationCompleted == null)) {
                this.cancelarAsincronoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarAsincronoOperationCompleted);
            }
            this.InvokeAsync("cancelarAsincrono", new object[] {
                        usuario,
                        password,
                        uuid,
                        rfcEmisor,
                        emailNotifica,
                        csdCer,
                        csdKey,
                        csdPassword,
                        properties}, this.cancelarAsincronoOperationCompleted, userState);
        }
        
        private void OncancelarAsincronoOperationCompleted(object arg) {
            if ((this.cancelarAsincronoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarAsincronoCompleted(this, new cancelarAsincronoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://binding.soap.cancelacion.commons.cfdi.solucionfactible.com/xsd")]
    public partial class KeyValue {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cfdi.solucionfactible.com/xsd")]
    public partial class CancelacionAsincronoResponse {
        
        private string mensajeField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://response.cancelacion.commons.timbrado.solucionfactible.com/xsd")]
    public partial class StatusCancelacionResponse {
        
        private byte[] acuseSatField;
        
        private string mensajeField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] acuseSat {
            get {
                return this.acuseSatField;
            }
            set {
                this.acuseSatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getStatusCancelacionAsincronaCompletedEventHandler(object sender, getStatusCancelacionAsincronaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusCancelacionAsincronaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCancelacionAsincronaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarSectorPrimarioCompletedEventHandler(object sender, cancelarSectorPrimarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarSectorPrimarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarSectorPrimarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void enviarSolicitudCancelacionAsincronoCompletedEventHandler(object sender, enviarSolicitudCancelacionAsincronoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSolicitudCancelacionAsincronoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSolicitudCancelacionAsincronoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelacionAsincronoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelacionAsincronoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void enviarSolicitudCancelacionCompletedEventHandler(object sender, enviarSolicitudCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSolicitudCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSolicitudCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarCompletedEventHandler(object sender, cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusCancelacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusCancelacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarAsincronoCompletedEventHandler(object sender, cancelarAsincronoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarAsincronoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarAsincronoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelacionAsincronoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelacionAsincronoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591