//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exitosw.Payroll.Core
{
    using System;
    using System.Reflection;
    using System.Web;
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigMascaras
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigMascaras()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                   // string nameProject = HttpContext.Current.ApplicationInstance.GetType().BaseType.Assembly.GetName().Name;
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exitosw.Payroll.Aplicacion.Api.ConfigMascaras", typeof(ConfigMascaras).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string BancosClave
        {
            get
            {
                return ResourceManager.GetString("BancosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string BancosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("BancosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string BancosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("BancosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string BancosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("BancosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a UUU-######-AAA.
        /// </summary>
        internal static string BancosRFC
        {
            get
            {
                return ResourceManager.GetString("BancosRFC", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string BancosRFCCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("BancosRFCCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string BancosRFCDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("BancosRFCDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string BancosRFCTipoMascara
        {
            get
            {
                return ResourceManager.GetString("BancosRFCTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string CampoDIMClave
        {
            get
            {
                return ResourceManager.GetString("CampoDIMClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string caracterAutoCompletado
        {
            get
            {
                return ResourceManager.GetString("caracterAutoCompletado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CaracterAutoCompletar
        {
            get
            {
                return ResourceManager.GetString("CaracterAutoCompletar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string CategoriasPuestosClave
        {
            get
            {
                return ResourceManager.GetString("CategoriasPuestosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CategoriasPuestosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CategoriasPuestosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CategoriasPuestosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CategoriasPuestosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CategoriasPuestosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CategoriasPuestosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string CentroDeCostoClave
        {
            get
            {
                return ResourceManager.GetString("CentroDeCostoClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CentroDeCostoClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CentroDeCostoClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CentroDeCostoClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CentroDeCostoClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CentroDeCostoClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CentroDeCostoClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ####.
        /// </summary>
        internal static string CiudadesClave
        {
            get
            {
                return ResourceManager.GetString("CiudadesClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CiudadesClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CiudadesClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CiudadesClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CiudadesClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CiudadesClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CiudadesClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string ConcepNomDefiClave
        {
            get
            {
                return ResourceManager.GetString("ConcepNomDefiClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string ConcepNomDefiClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ConcepNomDefiClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ConcepNomDefiClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ConcepNomDefiClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string ConcepNomDefiClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("ConcepNomDefiClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a #####.
        /// </summary>
        internal static string CpClave
        {
            get
            {
                return ResourceManager.GetString("CpClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CpClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CpClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CpClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CpClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CpClavePermitirModificarMascara
        {
            get
            {
                return ResourceManager.GetString("CpClavePermitirModificarMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CpClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CpClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string CreditoAhorroClave
        {
            get
            {
                return ResourceManager.GetString("CreditoAhorroClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CreditoAhorroClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CreditoAhorroClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ######.
        /// </summary>
        internal static string CruceClaveElemento
        {
            get
            {
                return ResourceManager.GetString("CruceClaveElemento", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CruceClaveElementoCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CruceClaveElementoCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CruceClaveElementoDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CruceClaveElementoDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CruceClaveElementoTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CruceClaveElementoTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string CuentasContablesClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CuentasContablesClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string CuentasContablesClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("CuentasContablesClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string CuentasContablesClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("CuentasContablesClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string DepartamentosClave
        {
            get
            {
                return ResourceManager.GetString("DepartamentosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string DepartamentosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("DepartamentosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string DepartamentosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("DepartamentosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string DepartamentosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("DepartamentosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string ElementosAplicacionClave
        {
            get
            {
                return ResourceManager.GetString("ElementosAplicacionClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string ElementosAplicacionClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ElementosAplicacionClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ElementosAplicacionClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ElementosAplicacionClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ElementosAplicacionClavePermitirModificarMascara
        {
            get
            {
                return ResourceManager.GetString("ElementosAplicacionClavePermitirModificarMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string ElementosAplicacionClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("ElementosAplicacionClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a #####.
        /// </summary>
        internal static string EmpleadosClave
        {
            get
            {
                return ResourceManager.GetString("EmpleadosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string EmpleadosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string EmpleadosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string EmpleadosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("EmpleadosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a UUUU-######-UUUUUUA#.
        /// </summary>
        internal static string EmpleadosCURP
        {
            get
            {
                return ResourceManager.GetString("EmpleadosCURP", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string EmpleadosCURPCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosCURPCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string EmpleadosCURPDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosCURPDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string EmpleadosCURPTipoMascara
        {
            get
            {
                return ResourceManager.GetString("EmpleadosCURPTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a UUUU-######-AAA.
        /// </summary>
        internal static string EmpleadosRFC
        {
            get
            {
                return ResourceManager.GetString("EmpleadosRFC", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string EmpleadosRFCCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosRFCCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string EmpleadosRFCDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EmpleadosRFCDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string EmpleadosRFCTipoMascara
        {
            get
            {
                return ResourceManager.GetString("EmpleadosRFCTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AAA.
        /// </summary>
        internal static string EstadosClave
        {
            get
            {
                return ResourceManager.GetString("EstadosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string EstadosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EstadosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string EstadosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("EstadosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string EstadosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("EstadosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ######.
        /// </summary>
        internal static string FiniquitosLiquidacionesClave
        {
            get
            {
                return ResourceManager.GetString("FiniquitosLiquidacionesClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string FiniquitosLiquidacionesClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("FiniquitosLiquidacionesClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string FiniquitosLiquidacionesClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("FiniquitosLiquidacionesClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string FiniquitosLiquidacionesClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("FiniquitosLiquidacionesClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ####.
        /// </summary>
        internal static string FormatoCnxContaClave
        {
            get
            {
                return ResourceManager.GetString("FormatoCnxContaClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string FormatoCnxContaClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("FormatoCnxContaClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string FormatoCnxContaClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("FormatoCnxContaClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string FormatoCnxContaClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("FormatoCnxContaClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string GrupoClave
        {
            get
            {
                return ResourceManager.GetString("GrupoClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string GrupoClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("GrupoClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string GrupoClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("GrupoClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string GrupoClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("GrupoClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string HorarioClave
        {
            get
            {
                return ResourceManager.GetString("HorarioClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string HorarioClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string HorarioClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string HorarioClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("HorarioClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a hh:mm a.
        /// </summary>
        internal static string HorarioHoraEntrada
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraEntrada", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string HorarioHoraEntradaCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraEntradaCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string HorarioHoraEntradaDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraEntradaDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a D.
        /// </summary>
        internal static string HorarioHoraEntradaTipoMascara
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraEntradaTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a hh:mm a.
        /// </summary>
        internal static string HorarioHoraSalida
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraSalida", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string HorarioHoraSalidaCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraSalidaCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string HorarioHoraSalidaDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraSalidaDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string HorarioHoraSalidaTipoMascara
        {
            get
            {
                return ResourceManager.GetString("HorarioHoraSalidaTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string mascarasBaseDatos
        {
            get
            {
                return ResourceManager.GetString("mascarasBaseDatos", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        internal static string ModuloClave
        {
            get
            {
                return ResourceManager.GetString("ModuloClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string ModuloClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ModuloClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ModuloClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("ModuloClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string ModuloClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("ModuloClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        internal static string MonedasClave
        {
            get
            {
                return ResourceManager.GetString("MonedasClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string MonedasClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("MonedasClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string MonedasClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("MonedasClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string MonedasClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("MonedasClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string MunicipiosClave
        {
            get
            {
                return ResourceManager.GetString("MunicipiosClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string MunicipiosClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("MunicipiosClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string MunicipiosClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("MunicipiosClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string MunicipiosClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("MunicipiosClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string NivelesClasificacionClave
        {
            get
            {
                return ResourceManager.GetString("NivelesClasificacionClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string NivelesClasificacionClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("NivelesClasificacionClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string NivelesClasificacionClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("NivelesClasificacionClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string NivelesClasificacionClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("NivelesClasificacionClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AAA.
        /// </summary>
        internal static string PaisesClave
        {
            get
            {
                return ResourceManager.GetString("PaisesClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PaisesClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PaisesClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string PaisesClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PaisesClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PaisesClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PaisesClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string PerfilesClave
        {
            get
            {
                return ResourceManager.GetString("PerfilesClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PerfilesClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PerfilesClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string PerfilesClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PerfilesClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PerfilesClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PerfilesClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string PeriodicidadClave
        {
            get
            {
                return ResourceManager.GetString("PeriodicidadClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PeriodicidadClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PeriodicidadClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string PeriodicidadClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PeriodicidadClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PeriodicidadClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PeriodicidadClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###.
        /// </summary>
        internal static string PeriodosNominaClave
        {
            get
            {
                return ResourceManager.GetString("PeriodosNominaClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PeriodosNominaClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PeriodosNominaClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string PeriodosNominaClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PeriodosNominaClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PeriodosNominaClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PeriodosNominaClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ##.
        /// </summary>
        internal static string PlazasClave
        {
            get
            {
                return ResourceManager.GetString("PlazasClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PlazasClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PlazasClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string PlazasClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PlazasClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PlazasClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PlazasClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ###############.
        /// </summary>
        internal static string PlazasPorEmpleadoClave
        {
            get
            {
                return ResourceManager.GetString("PlazasPorEmpleadoClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string PlazasPorEmpleadoClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("PlazasPorEmpleadoClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string PlazasPorEmpleadoClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("PlazasPorEmpleadoClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string String1CreditoAhorroClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("String1CreditoAhorroClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string String1CreditoAhorroClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("String1CreditoAhorroClaveTipoMascara", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AAA.
        /// </summary>
        internal static string TipoCorridaClave
        {
            get
            {
                return ResourceManager.GetString("TipoCorridaClave", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a _.
        /// </summary>
        internal static string TipoCorridaClaveCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("TipoCorridaClaveCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string TipoCorridaClaveDefinirCaracterMarcador
        {
            get
            {
                return ResourceManager.GetString("TipoCorridaClaveDefinirCaracterMarcador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string TipoCorridaClaveTipoMascara
        {
            get
            {
                return ResourceManager.GetString("TipoCorridaClaveTipoMascara", resourceCulture);
            }
        }
    }
}
