//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Exitosw.Payroll.Core.WsSolucionfactible {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimbradoSoap11Binding", Namespace="http://timbrado.ws.cfdi.solucionfactible.com")]
    public partial class Timbrado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelarPorNotaCreditoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarViaCSDAlmacenadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSolicitudCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarBase64OperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarBase64OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Timbrado() {
            this.Url = global::Exitosw.Payroll.Core.Properties.Settings.Default.Exitosw_Payroll_Core_WsSolucionfactible_Timbrado;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelarPorNotaCreditoCompletedEventHandler cancelarPorNotaCreditoCompleted;
        
        /// <remarks/>
        public event cancelarViaCSDAlmacenadoCompletedEventHandler cancelarViaCSDAlmacenadoCompleted;
        
        /// <remarks/>
        public event enviarSolicitudCancelacionCompletedEventHandler enviarSolicitudCancelacionCompleted;
        
        /// <remarks/>
        public event cancelarCompletedEventHandler cancelarCompleted;
        
        /// <remarks/>
        public event timbrarBase64CompletedEventHandler timbrarBase64Completed;
        
        /// <remarks/>
        public event timbrarCompletedEventHandler timbrarCompleted;
        
        /// <remarks/>
        public event cancelarBase64CompletedEventHandler cancelarBase64Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarPorNotaCredito", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDIResultadoCertificacion cancelarPorNotaCredito([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derCertCSD, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derKeyCSD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelarPorNotaCredito", new object[] {
                        usuario,
                        password,
                        uuid,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD});
            return ((CFDIResultadoCertificacion)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarPorNotaCreditoAsync(string usuario, string password, string uuid, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD) {
            this.cancelarPorNotaCreditoAsync(usuario, password, uuid, derCertCSD, derKeyCSD, contrasenaCSD, null);
        }
        
        /// <remarks/>
        public void cancelarPorNotaCreditoAsync(string usuario, string password, string uuid, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD, object userState) {
            if ((this.cancelarPorNotaCreditoOperationCompleted == null)) {
                this.cancelarPorNotaCreditoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarPorNotaCreditoOperationCompleted);
            }
            this.InvokeAsync("cancelarPorNotaCredito", new object[] {
                        usuario,
                        password,
                        uuid,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD}, this.cancelarPorNotaCreditoOperationCompleted, userState);
        }
        
        private void OncancelarPorNotaCreditoOperationCompleted(object arg) {
            if ((this.cancelarPorNotaCreditoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarPorNotaCreditoCompleted(this, new cancelarPorNotaCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarViaCSDAlmacenado", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelarViaCSDAlmacenado([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids) {
            object[] results = this.Invoke("cancelarViaCSDAlmacenado", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarViaCSDAlmacenadoAsync(string usuario, string password, string rfcEmisor, string[] uuids) {
            this.cancelarViaCSDAlmacenadoAsync(usuario, password, rfcEmisor, uuids, null);
        }
        
        /// <remarks/>
        public void cancelarViaCSDAlmacenadoAsync(string usuario, string password, string rfcEmisor, string[] uuids, object userState) {
            if ((this.cancelarViaCSDAlmacenadoOperationCompleted == null)) {
                this.cancelarViaCSDAlmacenadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarViaCSDAlmacenadoOperationCompleted);
            }
            this.InvokeAsync("cancelarViaCSDAlmacenado", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids}, this.cancelarViaCSDAlmacenadoOperationCompleted, userState);
        }
        
        private void OncancelarViaCSDAlmacenadoOperationCompleted(object arg) {
            if ((this.cancelarViaCSDAlmacenadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarViaCSDAlmacenadoCompleted(this, new cancelarViaCSDAlmacenadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:enviarSolicitudCancelacion", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion enviarSolicitudCancelacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] solicitudCancelacion) {
            object[] results = this.Invoke("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitudCancelacion});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSolicitudCancelacionAsync(string usuario, string password, byte[] solicitudCancelacion) {
            this.enviarSolicitudCancelacionAsync(usuario, password, solicitudCancelacion, null);
        }
        
        /// <remarks/>
        public void enviarSolicitudCancelacionAsync(string usuario, string password, byte[] solicitudCancelacion, object userState) {
            if ((this.enviarSolicitudCancelacionOperationCompleted == null)) {
                this.enviarSolicitudCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSolicitudCancelacionOperationCompleted);
            }
            this.InvokeAsync("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitudCancelacion}, this.enviarSolicitudCancelacionOperationCompleted, userState);
        }
        
        private void OnenviarSolicitudCancelacionOperationCompleted(object arg) {
            if ((this.enviarSolicitudCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSolicitudCancelacionCompleted(this, new enviarSolicitudCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelar", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derCertCSD, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] derKeyCSD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelar", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsync(string usuario, string password, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD) {
            this.cancelarAsync(usuario, password, uuids, derCertCSD, derKeyCSD, contrasenaCSD, null);
        }
        
        /// <remarks/>
        public void cancelarAsync(string usuario, string password, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD, object userState) {
            if ((this.cancelarOperationCompleted == null)) {
                this.cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarOperationCompleted);
            }
            this.InvokeAsync("cancelar", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD}, this.cancelarOperationCompleted, userState);
        }
        
        private void OncancelarOperationCompleted(object arg) {
            if ((this.cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCompleted(this, new cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:timbrarBase64", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICertificacion timbrarBase64([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfdiBase64, bool zip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool zipSpecified) {
            object[] results = this.Invoke("timbrarBase64", new object[] {
                        usuario,
                        password,
                        cfdiBase64,
                        zip,
                        zipSpecified});
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarBase64Async(string usuario, string password, string cfdiBase64, bool zip, bool zipSpecified) {
            this.timbrarBase64Async(usuario, password, cfdiBase64, zip, zipSpecified, null);
        }
        
        /// <remarks/>
        public void timbrarBase64Async(string usuario, string password, string cfdiBase64, bool zip, bool zipSpecified, object userState) {
            if ((this.timbrarBase64OperationCompleted == null)) {
                this.timbrarBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarBase64OperationCompleted);
            }
            this.InvokeAsync("timbrarBase64", new object[] {
                        usuario,
                        password,
                        cfdiBase64,
                        zip,
                        zipSpecified}, this.timbrarBase64OperationCompleted, userState);
        }
        
        private void OntimbrarBase64OperationCompleted(object arg) {
            if ((this.timbrarBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarBase64Completed(this, new timbrarBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:timbrar", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICertificacion timbrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] cfdi, bool zip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool zipSpecified) {
            object[] results = this.Invoke("timbrar", new object[] {
                        usuario,
                        password,
                        cfdi,
                        zip,
                        zipSpecified});
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarAsync(string usuario, string password, byte[] cfdi, bool zip, bool zipSpecified) {
            this.timbrarAsync(usuario, password, cfdi, zip, zipSpecified, null);
        }
        
        /// <remarks/>
        public void timbrarAsync(string usuario, string password, byte[] cfdi, bool zip, bool zipSpecified, object userState) {
            if ((this.timbrarOperationCompleted == null)) {
                this.timbrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarOperationCompleted);
            }
            this.InvokeAsync("timbrar", new object[] {
                        usuario,
                        password,
                        cfdi,
                        zip,
                        zipSpecified}, this.timbrarOperationCompleted, userState);
        }
        
        private void OntimbrarOperationCompleted(object arg) {
            if ((this.timbrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarCompleted(this, new timbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarBase64", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelarBase64([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string derCertCSDBase64, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string derKeyCSDBase64, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelarBase64", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSDBase64,
                        derKeyCSDBase64,
                        contrasenaCSD});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarBase64Async(string usuario, string password, string[] uuids, string derCertCSDBase64, string derKeyCSDBase64, string contrasenaCSD) {
            this.cancelarBase64Async(usuario, password, uuids, derCertCSDBase64, derKeyCSDBase64, contrasenaCSD, null);
        }
        
        /// <remarks/>
        public void cancelarBase64Async(string usuario, string password, string[] uuids, string derCertCSDBase64, string derKeyCSDBase64, string contrasenaCSD, object userState) {
            if ((this.cancelarBase64OperationCompleted == null)) {
                this.cancelarBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarBase64OperationCompleted);
            }
            this.InvokeAsync("cancelarBase64", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSDBase64,
                        derKeyCSDBase64,
                        contrasenaCSD}, this.cancelarBase64OperationCompleted, userState);
        }
        
        private void OncancelarBase64OperationCompleted(object arg) {
            if ((this.cancelarBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarBase64Completed(this, new cancelarBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDIResultadoCertificacion {
        
        private string cadenaOriginalField;
        
        private string certificadoSATField;
        
        private byte[] cfdiTimbradoField;
        
        private System.Nullable<System.DateTime> fechaTimbradoField;
        
        private bool fechaTimbradoFieldSpecified;
        
        private string mensajeField;
        
        private byte[] qrCodeField;
        
        private string selloSATField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private string uuidField;
        
        private string versionTFDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string certificadoSAT {
            get {
                return this.certificadoSATField;
            }
            set {
                this.certificadoSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cfdiTimbrado {
            get {
                return this.cfdiTimbradoField;
            }
            set {
                this.cfdiTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaTimbrado {
            get {
                return this.fechaTimbradoField;
            }
            set {
                this.fechaTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaTimbradoSpecified {
            get {
                return this.fechaTimbradoFieldSpecified;
            }
            set {
                this.fechaTimbradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] qrCode {
            get {
                return this.qrCodeField;
            }
            set {
                this.qrCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string selloSAT {
            get {
                return this.selloSATField;
            }
            set {
                this.selloSATField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string versionTFD {
            get {
                return this.versionTFDField;
            }
            set {
                this.versionTFDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDICertificacion {
        
        private string mensajeField;
        
        private CFDIResultadoCertificacion[] resultadosField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true)]
        public CFDIResultadoCertificacion[] resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDIResultadoCancelacion {
        
        private string mensajeField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private string statusUUIDField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusUUID {
            get {
                return this.statusUUIDField;
            }
            set {
                this.statusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDICancelacion {
        
        private string mensajeField;
        
        private CFDIResultadoCancelacion[] resultadosField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true)]
        public CFDIResultadoCancelacion[] resultados {
            get {
                return this.resultadosField;
            }
            set {
                this.resultadosField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarPorNotaCreditoCompletedEventHandler(object sender, cancelarPorNotaCreditoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarPorNotaCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarPorNotaCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDIResultadoCertificacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDIResultadoCertificacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarViaCSDAlmacenadoCompletedEventHandler(object sender, cancelarViaCSDAlmacenadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarViaCSDAlmacenadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarViaCSDAlmacenadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void enviarSolicitudCancelacionCompletedEventHandler(object sender, enviarSolicitudCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSolicitudCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSolicitudCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarCompletedEventHandler(object sender, cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICancelacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void timbrarBase64CompletedEventHandler(object sender, timbrarBase64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICertificacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICertificacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void timbrarCompletedEventHandler(object sender, timbrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICertificacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICertificacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarBase64CompletedEventHandler(object sender, cancelarBase64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CFDICancelacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CFDICancelacion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591