using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Exitosw.Payroll.Core.CFDI.Sat.Catalogos
{
    public enum CMoneda
    {
        [Description("AED")]
        AED,
        [Description("AFN")]
        AFN,
        [Description("ALL")]
        ALL,
        [Description("AMD")]
        AMD,
        [Description("ANG")]
        ANG,
        [Description("AOA")]
        AOA,
        [Description("ARS")]
        ARS,
        [Description("AUD")]
        AUD,
        [Description("AWG")]
        AWG,
        [Description("AZN")]
        AZN,
        [Description("BAM")]
        BAM,
        [Description("BBD")]
        BBD,
        [Description("BDT")]
        BDT,
        [Description("BGN")]
        BGN,
        [Description("BHD")]
        BHD,
        [Description("BIF")]
        BIF,
        [Description("BMD")]
        BMD,
        [Description("BND")]
        BND,
        [Description("BOB")]
        BOB,
        [Description("BOV")]
        BOV,
        [Description("BRL")]
        BRL,
        [Description("BSD")]
        BSD,
        [Description("BTN")]
        BTN,
        [Description("BWP")]
        BWP,
        [Description("BYR")]
        BYR,
        [Description("BZD")]
        BZD,
        [Description("CAD")]
        CAD,
        [Description("CDF")]
        CDF,
        [Description("CHE")]
        CHE,
        [Description("CHF")]
        CHF,
        [Description("CHW")]
        CHW,
        [Description("CLF")]
        CLF,
        [Description("CLP")]
        CLP,
        [Description("CNY")]
        CNY,
        [Description("COP")]
        COP,
        [Description("COU")]
        COU,
        [Description("CRC")]
        CRC,
        [Description("CUC")]
        CUC,
        [Description("CUP")]
        CUP,
        [Description("CVE")]
        CVE,
        [Description("CZK")]
        CZK,
        [Description("DJF")]
        DJF,
        [Description("DKK")]
        DKK,
        [Description("DOP")]
        DOP,
        [Description("DZD")]
        DZD,
        [Description("EGP")]
        EGP,
        [Description("ERN")]
        ERN,
        [Description("ETB")]
        ETB,
        [Description("EUR")]
        EUR,
        [Description("FJD")]
        FJD,
        [Description("FKP")]
        FKP,
        [Description("GBP")]
        GBP,
        [Description("GEL")]
        GEL,
        [Description("GHS")]
        GHS,
        [Description("GIP")]
        GIP,
        [Description("GMD")]
        GMD,
        [Description("GNF")]
        GNF,
        [Description("GTQ")]
        GTQ,
        [Description("GYD")]
        GYD,
        [Description("HKD")]
        HKD,
        [Description("HNL")]
        HNL,
        [Description("HRK")]
        HRK,
        [Description("HTG")]
        HTG,
        [Description("HUF")]
        HUF,
        [Description("IDR")]
        IDR,
        [Description("ILS")]
        ILS,
        [Description("INR")]
        INR,
        [Description("IQD")]
        IQD,
        [Description("IRR")]
        IRR,
        [Description("ISK")]
        ISK,
        [Description("JMD")]
        JMD,
        [Description("JOD")]
        JOD,
        [Description("JPY")]
        JPY,
        [Description("KES")]
        KES,
        [Description("KGS")]
        KGS,
        [Description("KHR")]
        KHR,
        [Description("KMF")]
        KMF,
        [Description("KPW")]
        KPW,
        [Description("KRW")]
        KRW,
        [Description("KWD")]
        KWD,
        [Description("KYD")]
        KYD,
        [Description("KZT")]
        KZT,
        [Description("LAK")]
        LAK,
        [Description("LBP")]
        LBP,
        [Description("LKR")]
        LKR,
        [Description("LRD")]
        LRD,
        [Description("LSL")]
        LSL,
        [Description("LYD")]
        LYD,
        [Description("MAD")]
        MAD,
        [Description("MDL")]
        MDL,
        [Description("MGA")]
        MGA,
        [Description("MKD")]
        MKD,
        [Description("MMK")]
        MMK,
        [Description("MNT")]
        MNT,
        [Description("MOP")]
        MOP,
        [Description("MRO")]
        MRO,
        [Description("MUR")]
        MUR,
        [Description("MVR")]
        MVR,
        [Description("MWK")]
        MWK,
        [Description("MXN")]
        MXN,
        [Description("MXV")]
        MXV,
        [Description("MYR")]
        MYR,
        [Description("MZN")]
        MZN,
        [Description("NAD")]
        NAD,
        [Description("NGN")]
        NGN,
        [Description("NIO")]
        NIO,
        [Description("NOK")]
        NOK,
        [Description("NPR")]
        NPR,
        [Description("NZD")]
        NZD,
        [Description("OMR")]
        OMR,
        [Description("PAB")]
        PAB,
        [Description("PEN")]
        PEN,
        [Description("PGK")]
        PGK,
        [Description("PHP")]
        PHP,
        [Description("PKR")]
        PKR,
        [Description("PLN")]
        PLN,
        [Description("PYG")]
        PYG,
        [Description("QAR")]
        QAR,
        [Description("RON")]
        RON,
        [Description("RSD")]
        RSD,
        [Description("RUB")]
        RUB,
        [Description("RWF")]
        RWF,
        [Description("SAR")]
        SAR,
        [Description("SBD")]
        SBD,
        [Description("SCR")]
        SCR,
        [Description("SDG")]
        SDG,
        [Description("SEK")]
        SEK,
        [Description("SGD")]
        SGD,
        [Description("SHP")]
        SHP,
        [Description("SLL")]
        SLL,
        [Description("SOS")]
        SOS,
        [Description("SRD")]
        SRD,
        [Description("SSP")]
        SSP,
        [Description("STD")]
        STD,
        [Description("SVC")]
        SVC,
        [Description("SYP")]
        SYP,
        [Description("SZL")]
        SZL,
        [Description("THB")]
        THB,
        [Description("TJS")]
        TJS,
        [Description("TMT")]
        TMT,
        [Description("TND")]
        TND,
        [Description("TOP")]
        TOP,
        [Description("TRY")]
        TRY,
        [Description("TTD")]
        TTD,
        [Description("TWD")]
        TWD,
        [Description("TZS")]
        TZS,
        [Description("UAH")]
        UAH,
        [Description("UGX")]
        UGX,
        [Description("USD")]
        USD,
        [Description("USN")]
        USN,
        [Description("UYI")]
        UYI,
        [Description("UYU")]
        UYU,
        [Description("UZS")]
        UZS,
        [Description("VEF")]
        VEF,
        [Description("VND")]
        VND,
        [Description("VUV")]
        VUV,
        [Description("WST")]
        WST,
        [Description("XAF")]
        XAF,
        [Description("XAG")]
        XAG,
        [Description("XAU")]
        XAU,
        [Description("XBA")]
        XBA,
        [Description("XBB")]
        XBB,
        [Description("XBC")]
        XBC,
        [Description("XBD")]
        XBD,
        [Description("XCD")]
        XCD,
        [Description("XDR")]
        XDR,
        [Description("XOF")]
        XOF,
        [Description("XPD")]
        XPD,
        [Description("XPF")]
        XPF,
        [Description("XPT")]
        XPT,
        [Description("XSU")]
        XSU,
        [Description("XTS")]
        XTS,
        [Description("XUA")]
        XUA,
        [Description("XXX")]
        XXX,
        [Description("YER")]
        YER,
        [Description("ZAR")]
        ZAR,
        [Description("ZMW")]
        ZMW,
        [Description("ZWL")]
        ZWL,
    }
}
